version: '3'
volumes:
  db_data:

services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 
    volumes:
      - "./:/docker-entrypoint-initdb.d"
      - db_data:/var/lib/mysql
    ports:
      - 8080:80
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" 
    ports:
      - 3360:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306